import type { FieldVisit, ServiceRequest, Task, UserProfile } from './types';

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Irrigation System Check',
    field: 'North Field A',
    description: 'Inspect pumps, valves, and drip lines for leaks and pressure stability.',
    status: 'In Progress',
    harvestDate: 'Jan 25, 2026',
    progress: 65,
    color: 'red',
    icon: 'droplet',
  },
  {
    id: 't2',
    title: 'Fertilizer Application',
    field: 'South Field B',
    description: 'Apply nitrogen blend and ensure spreader calibration is within spec.',
    status: 'Pending',
    harvestDate: 'Feb 10, 2026',
    color: 'amber',
    icon: 'sprout',
  },
  {
    id: 't3',
    title: 'Pest Control Inspection',
    field: 'East Greenhouse',
    description: 'Check sticky traps and evaluate leaf damage for early pest signs.',
    status: 'In Progress',
    harvestDate: 'Jan 30, 2026',
    progress: 40,
    color: 'green',
    icon: 'bug',
  },
  {
    id: 't4',
    title: 'Equipment Maintenance',
    field: 'Tractor Bay 2',
    description: 'Perform oil check, belt tension review, and hydraulic fluid inspection.',
    status: 'Urgent',
    color: 'blue',
    icon: 'tractor',
  },
  {
    id: 't5',
    title: 'Soil Testing',
    field: 'West Field C',
    description: 'Collect soil samples at 10m intervals for pH and nutrient profiling.',
    status: 'Pending',
    harvestDate: 'Feb 15, 2026',
    color: 'purple',
    icon: 'filetext',
  },
  {
    id: 't6',
    title: 'Harvest Planning',
    field: 'North Field A',
    description: 'Finalize crew schedule and storage allocation for upcoming harvest window.',
    status: 'In Progress',
    harvestDate: 'Jan 25, 2026',
    progress: 80,
    color: 'pink',
    icon: 'package',
  },
];

export const mockVisits: FieldVisit[] = [
  {
    id: 'v1',
    fieldName: 'Field A - North Section',
    supervisor: 'Sarah Martinez',
    date: 'Jan 18, 2026',
    time: '09:30 AM',
    crop: 'Wheat',
    status: 'Completed',
    findings:
      'Healthy crop growth observed. Slight pest activity detected in northeast corner. Recommend monitoring.',
    gradient: 'indigo',
  },
  {
    id: 'v2',
    fieldName: 'Greenhouse 2',
    supervisor: 'Mike Johnson',
    date: 'Jan 18, 2026',
    time: '02:00 PM',
    crop: 'Tomatoes',
    status: 'Scheduled',
    findings: 'Upcoming inspection. Review irrigation timing and humidity levels before visit.',
    gradient: 'cyan',
  },
  {
    id: 'v3',
    fieldName: 'Field B - East',
    supervisor: 'Sarah Martinez',
    date: 'Jan 17, 2026',
    time: '11:15 AM',
    crop: 'Corn',
    status: 'Completed',
    findings: 'Irrigation unevenness noted in row 12-18. Suggested nozzle replacement and recalibration.',
    gradient: 'orange',
  },
  {
    id: 'v4',
    fieldName: 'Field C - West',
    supervisor: 'David Chen',
    date: 'Jan 19, 2026',
    time: '08:00 AM',
    crop: 'Soybeans',
    status: 'Scheduled',
    findings: 'Routine check planned. Verify fertilizer logs and pest treatment history.',
    gradient: 'green',
  },
  {
    id: 'v5',
    fieldName: 'Greenhouse 1',
    supervisor: 'Mike Johnson',
    date: 'Jan 16, 2026',
    time: '03:30 PM',
    crop: 'Cucumbers',
    status: 'Overdue',
    findings: 'Requires follow-up. Nutrient deficiencies suspected; leaf yellowing increasing.',
    gradient: 'pink',
    highPriority: true,
  },
];

export const mockServices: ServiceRequest[] = [
  {
    id: 's1',
    requestId: '#SR-2401',
    title: 'Tractor Repair Service',
    category: 'Equipment',
    requestedDate: 'Jan 15, 2026',
    priority: 'High',
    status: 'In Progress',
    description: 'Transmission noise and intermittent power loss during load operations.',
    assignedTo: 'Agent: John Doe',
    color: 'rose',
    icon: 'wrench',
  },
  {
    id: 's2',
    requestId: '#SR-2402',
    title: 'Agronomist Consultation',
    category: 'Consultation',
    requestedDate: 'Jan 16, 2026',
    priority: 'Medium',
    status: 'Pending',
    description: 'Request soil nutrient and crop rotation recommendations for spring season.',
    color: 'violet',
    icon: 'users',
  },
  {
    id: 's3',
    requestId: '#SR-2403',
    title: 'Fertilizer Delivery',
    category: 'Supplies',
    requestedDate: 'Jan 14, 2026',
    priority: 'Low',
    status: 'Completed',
    description: 'Deliver 30 bags of NPK blend, confirm drop-off at storage shed.',
    assignedTo: 'Agent: Priya Singh',
    color: 'teal',
    icon: 'package',
  },
  {
    id: 's4',
    requestId: '#SR-2404',
    title: 'Irrigation Maintenance',
    category: 'Maintenance',
    requestedDate: 'Jan 17, 2026',
    priority: 'High',
    status: 'Processing',
    description: 'Inspect mainline filters and replace worn drippers in greenhouse zone 3.',
    color: 'orange',
    icon: 'settings',
  },
  {
    id: 's5',
    requestId: '#SR-2405',
    title: 'Seed Order',
    category: 'Supplies',
    requestedDate: 'Jan 13, 2026',
    priority: 'Medium',
    status: 'Completed',
    description: 'Order certified soybean seeds (variety S-21) for 40 acres coverage.',
    color: 'blue',
    icon: 'truck',
  },
  {
    id: 's6',
    requestId: '#SR-2406',
    title: 'Soil Analysis',
    category: 'Consultation',
    requestedDate: 'Jan 18, 2026',
    priority: 'High',
    status: 'Pending',
    description: 'Send samples for lab analysis and provide amendment recommendation report.',
    color: 'fuchsia',
    icon: 'tool',
  },
];

export const mockProfile: UserProfile = {
  name: 'John Farmer',
  role: 'Farm Manager',
  email: 'john.farmer@farmconnect.com',
  phone: '+1 (555) 123-4567',
  location: 'California, USA',
  memberSince: 'January 2024',
  farmName: 'Sunny Acres Farm',
  totalArea: '150 acres',
  primaryCrops: 'Wheat, Corn, Soybeans',
  livestock: '50 Cattle, 200 Chickens',
  stats: {
    fields: 8,
    tasks: 12,
    efficiency: '94%',
  },
};

// Dummy data removed. This app now loads data from backend APIs.
// If you still need local fallback data for offline mode, reintroduce it here.

export {};
